import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "@/components/side-menu";
import { ThemeProvider } from "@/providers/themeProvider";
import { ModeToggle } from "@/components/mode-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smarthub | Sprint monitoring",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex w-full h-screen">
            <SideMenu />
            {children}
            <div className="fixed top-8 right-8">
              <ModeToggle />
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
