import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SideMenu from "@/components/side-menu";
import { ThemeProvider } from "@/providers/themeProvider";
import { ModeToggle } from "@/components/mode-toggle";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Smarthub | Sprint monitoring",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${poppins.className} h-full`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex w-full min-h-screen">
            <SideMenu />
            {children}
            <div className="fixed top-8 right-8">
              <ModeToggle />
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
